### ISSUE TITLE
Can't run make without including Zheng data sets

### ISSUE THREAD

**Issue by JohnReid** [markrobinsonuzh/scRNAseq_clustering_comparison#4]
I tried to change `include_datasets.mk` to ignore the large data sets as in the README but the `summarise` rule in the `Makefile` depends on the `scalability_$(m)` rules that themselves depend on `data/sce_filteredExpr10/sce_filteredExpr10_Zhengmix4uneq.rds`. This target is not defined when the Zheng data is excluded in `include_datasets.mk`.

**Comment by csoneson** [comment]
Yes, all the scalability calculations are done using the largest Zheng data set (we needed a big enough data set for these calculations to be informative). You can just remove `$(foreach m,$(METHODS),output/scalability/scalability_$(m).rds)` from the `summarise` target (and `plots/scalability/scalability.rds` from the `figs` target) if you don't want to do the scalability calculations.
