### ISSUE TITLE
Quitting from lines 45-53 (import_QC_Kumar.Rmd)

### ISSUE THREAD

**Issue by chenxofhit** [markrobinsonuzh/scRNAseq_clustering_comparison#5]
➜  scRNAseq_clustering_comparison git:(master) ✗ make
cd Rscripts/import_datasets && /usr/local/bin/Rscript --no-restore --no-save -e "rmarkdown::render('import_QC_Kumar.Rmd', clean = TRUE)"

processing file: import_QC_Kumar.Rmd
  |..                                                               |   3%
  ordinary text without R code

  |....                                                             |   6%
label: load-packages
  |......                                                           |   9%
  ordinary text without R code

  |........                                                         |  12%
label: load-dataset
  |..........                                                       |  15%
  ordinary text without R code

  |............                                                     |  18%
label: create-sce
Quitting from lines 45-53 (import_QC_Kumar.Rmd)
Error in .local(object, ...) : 参数没有用(return_norm_as_exprs = TRUE)
Calls: <Anonymous> ... eval -> eval -> normalise -> normalize -> normalize

停止执行
make: *** [data/sce_full/sce_full_Kumar.rds] Error 1

The above message are directly copied from the console  output.
I translate the Chinese characters as the following:
参数没有用:  Parameters are in no use;
停止执行：Stop execution.

The normalization function seems to not work   as expected.

**Comment by csoneson** [comment]
This is because in the new version of scater, this argument is no longer in use (we used scater v 1.6.0 to preprocess the data sets) Probably the easiest option is to check out the `updates` branch instead, where this issue has been fixed and the code runs with scater v 1.8.0.

**Comment by chenxofhit** [comment]
> This is because in the new version of scater, this argument is no longer in use (we used scater v 1.6.0 to preprocess the data sets) Probably the easiest option is to check out the `updates` branch instead, where this issue has been fixed and the code runs with scater v 1.8.0.

It works now.  @csoneson Thank you very much.
The issue should be closed now.
