### ISSUE TITLE
Got error 126 when running make setup 

### ISSUE THREAD

**Issue by SSooop** [markrobinsonuzh/scRNAseq_clustering_comparison#6]
Conda environment with R version 3.5.0 and Rscript 3.4.2
I have finished installing all the packages list below with the default version for BiocManager version=3.7, but I can't go through the "Instructions for running the code" part. I have set my Makefile as:
Rscript := /home/my/miniconda3/env/myRenv3_4/Rscript --no-restore --no-save
R := R_LIBS=Rlibrary3.5 /home/my/miniconda3/lib/R/R-3.5.0/bin/R CMD BATCH --no-restore --no-save
and I will get an error after running make setup and downloading all the raw data
R_LIBS=Rlibrary3.5 /home/my/miniconda3/lib/R CMD BATCH Rscripts/parameter_settings/generate_parameter_settings.R Rout/generate_parameter_settings.Rout                    
/bin/sh: 1: /home/my/miniconda3/lib/R: Permission denied
make: *** [Makefile:67: setup] Error 126

**Comment by csoneson** [comment]
This looks like a conda issue rather than something related to our workflow. Can you run R interactively, i.e. does 
```
R_LIBS=Rlibrary3.5 /home/my/miniconda3/lib/R
```
open an R session? Did you install conda as an administrator?

**Comment by SSooop** [comment]
> This looks like a conda issue rather than something related to our workflow. Can you run R interactively, i.e. does
> 
> ```
> R_LIBS=Rlibrary3.5 /home/my/miniconda3/lib/R
> ```
> 
> open an R session? Did you install conda as an administrator?
