### ISSUE TITLE
Dataset not accessible

### ISSUE THREAD

**Issue by dmatijev** [markrobinsonuzh/scRNAseq_clustering_comparison#7]
It seems that the dataset has been removed from http://imlspenticton.uzh.ch/robinson_lab/DuoClustering2018/DuoClustering2018.tar.gz. Is there any other way to download the dataset?

Thanks!

**Comment by csoneson** [comment]
Hi, thanks for flagging this and apologies - the data should be accessible again. Note that you can also access the data via the `DuoClustering2018` Bioconductor package: https://bioconductor.org/packages/DuoClustering2018/
